### ISSUE TITLE
How to call a function after a date is selected ?

### ISSUE THREAD

**Issue by kiransalian91** [MariemChaabeni/angular-calendar-year-view#2]
@MariemChaabeni  I need to call a function in .ts file after a date is selected. and hide default popup which is used in angular-calendar-year-view.js file.  and have a custom popup.

**Comment by MariemChaabeni** [comment]
Hello, 
1-How to call a function after a date is selected ?  
     May I need to add an output onDateClicked 
2-Use custom popup
  I'm actually working on this, it will be ready by the next version 2 of package .

It will be avalebal soon 😄 
https://www.npmjs.com/package/angular-calendar-year-view

**Comment by kiransalian91** [comment]
> Hello,
> 1-How to call a function after a date is selected ?
> May I need to add an output onDateClicked
> 2-Use custom popup
> I'm actually working on this, it will be ready by the next version 2 of package .
> 
> It will be available soon 
> https://www.npmjs.com/package/angular-calendar-year-view

**Comment by kiransalian91** [comment]
Yes. we need a output on DateClicked. so that we can handle it in our component.

**Comment by MariemChaabeni** [comment]
@kiransalian91   hello, the v2 is here now https://www.npmjs.com/package/angular-calendar-year-view

**Comment by kiransalian91** [comment]
@MariemChaabeni Thank you. this solved my issue :)
